### ISSUE TITLE
Allow using as a command line app rather in addition to an interactive shell

### ISSUE THREAD

**Issue by cool-RR** [getoutofmyyard/igloo#3]
To be honest I have no idea why Igloo is build as a shell. Care to explain?

**Comment by getoutofmyyard** [comment]
That's a great idea. Igloo is built as a shell because that's what I knew how to do, frankly. It's feedback like yours that will help make the app better, so I appreciate it.

**Comment by cool-RR** [comment]
Cool. Looking at the code, I think you've reinvented a bunch of things, and it'll be better if you'd use a standard solution, like the click framework. I also see a bunch of code smells. If you'll want me to write some notes, let me know.

**Comment by getoutofmyyard** [comment]
That would be an excellent help. Thanks!

**Comment by cool-RR** [comment]
1. As said before, use `click`. Go over the tutorial and actually write the code: https://click.palletsprojects.com/en/7.x/ There are some advanced features like [groups.](https://click.palletsprojects.com/en/7.x/commands/) It might take a while to understand them, but basically they'll let you do things automatically that you're right now working very hard to do.
2. Make a commit to remove all the pyc files and __pycache__ folders from your repo. Then add a `.gitignore` file. I see you've done this before and reverted? Maybe because you first added the file and then tried to remove the junk. You can copy my `.gitignore` from here: https://github.com/cool-RR/PySnooper/
3. All your code should be in a package (folder) called igloo instead of your repo root. You can copy the structure from my project: https://github.com/cool-RR/PySnooper/
4. No capital letters in module names. Instead of `helpDict.py` you should have `help_dict.py`, assuming this file will even need to exist after using `click`.
5. You need tests. This is going to be hard because this is a systems program. It's possible, and if you intend to continue development long-term, it'll be worth it. But it'll be a big project to add it. 
6. Your program is somewhat similar to [Wizmo](https://www.grc.com/wizmo/wizmo.htm) , you might find interesting things there.
7. When you do use `click`, you can use the [`click-shell`](https://github.com/clarkperkins/click-shell) extension that'll automatically make a shell for you, instead of you having to do it manually.
8. Looking at the code (`main.py` right now) there's lots of bad patterns, like using way too many bare `except`s. Your function `cli` has a way too long `if-elif`. But after you'll move to `click`, many of these will be gone.

If you do reach the stage where you fixed most of these, you can ask me for a review again. Your code would look totally different and much easier to reason about.

**Comment by getoutofmyyard** [comment]
Thanks very much for your thoughtful advice!

**Comment by getoutofmyyard** [comment]
Added persistent "igloo" alias config upon launch. Terminal app functionality is now enabled from PowerShell (or cmd if in the program directory).
